# Generated by Django 5.1.2 on 2024-10-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0002_remove_person_first_name_remove_person_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
