# Generated by Django 5.1.2 on 2024-11-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0006_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
