# Generated by Django 5.1.2 on 2024-11-30 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0007_movie_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
