# Generated by Django 5.1.2 on 2024-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0009_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='black_and_white',
            field=models.BooleanField(default=False),
        ),
    ]
