# Generated by Django 5.1.2 on 2024-12-29 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0010_movie_black_and_white'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Co2CalculatorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromCity', models.CharField(max_length=500)),
                ('toCity', models.CharField(max_length=500)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co2calc_histories', to=settings.AUTH_USER_MODEL)),
                ('distanceMode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mode', to='yamod.distancemode')),
            ],
        ),
        migrations.CreateModel(
            name='PolutionUserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=500)),
                ('polutionIndex', models.IntegerField()),
                ('coValue', models.DecimalField(decimal_places=3, max_digits=10)),
                ('no2Value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('o3Value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('so2Value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pm25Value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pm10Value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('nh3Value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollution_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
