# Generated by Django 5.1.2 on 2024-12-30 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0011_distancemode_co2calculatorhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polutionuserhistory',
            name='dateValue',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
