# Generated by Django 5.1.2 on 2024-12-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0013_rename_datevalue_polutionuserhistory_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polutionuserhistory',
            old_name='date',
            new_name='dateValue',
        ),
    ]
