# Generated by Django 5.1.4 on 2024-12-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0014_rename_date_polutionuserhistory_datevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2calculatorhistory',
            name='co2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
