# Generated by Django 5.1.4 on 2025-01-03 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0015_co2calculatorhistory_co2'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2calculatorhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
