# Generated by Django 5.1.2 on 2025-01-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0016_co2calculatorhistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
