# Generated by Django 5.1.2 on 2025-01-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0020_userprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='distancemode',
            name='emission_factor',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='distancemode',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
