# Generated by Django 5.1.2 on 2025-01-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0021_distancemode_emission_factor_alter_distancemode_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distancemode',
            name='emission_factor',
        ),
        migrations.AlterField(
            model_name='distancemode',
            name='name',
            field=models.CharField(max_length=4096),
        ),
    ]
