# Generated by Django 5.1.2 on 2025-01-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0022_remove_distancemode_emission_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2calculatorhistory',
            name='distance',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
