# Generated by Django 5.1.2 on 2025-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0023_alter_co2calculatorhistory_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2calculatorhistory',
            name='co2',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
